# 数据源配置
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8 #连接池最大连接数
        max-idle: 8 #连接池最大空闲连接数
        min-idle: 0 #连接池最小空闲连接数
        max-wait: -1ms #连接池最大阻塞等待时间,负值表示没有限制
  datasource:
    url: jdbc:postgresql://rm-2zefzzv3s8d74dyfvho.pg.rds.aliyuncs.com:3432/arnaya_web_dev
    username: aranya_staging
    password: e23TsmZasGyEAqd2018
    driver-class-name: org.postgresql.Driver
#    schema:
#      - classpath:sql/dep.sql

# MyBatis mapper.xml路径配置
mybatis:
  mapper-locations:
    - classpath:com/**/dao/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  tokenHeader: token #JWT存储的请求头Authorization
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
qiniu:
  accessKey: M91phdlUiwtWi37PvU9-3kgeKs2vcfk61XkolT60
  secretKey: Riy5luwvrxxp22H84GLnGiyopykVZJTTln-UcEhs
  bucket: develop
  domain: qiniudevelop.aranya.cc
  zone: huadong
  url: http://qiniudevelop.aranya.cc/
host:
  url: https://spring-test.cc/
logging: #logback配置
  config: classpath:logback-spring.xml